version: "3"

services:
  nodejs:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app # set path use with volumes
    container_name: udemy-node
    ports:
      - "3000:3000"
    command: ["/bin/sh", "-c", "yarn && yarn start"]
  # mysql:
  #   image: mysql:5.7.22
  #   container_name: gokart-mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./database/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: gokart-mysql
# use [ docker network create nodejs-network ] เพื่อสร้าง mapmagiccloud(your network name) network ขึ้นมาก่อน
networks:
    default:
        external:
            name: nodejs-network
